# https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually
# https://mamba.readthedocs.io/en/latest/user_guide/troubleshooting.html#using-the-defaults-channels

name: asr-scripts
channels:
  - conda-forge
  - nodefaults
dependencies:
  # https://anaconda.org/conda-forge/python?version=3.10.14
  - python=3.10.14
  # https://github.com/python/cpython/blob/v3.10.14/Lib/ensurepip/__init__.py#L15
  - pip=23.0.1
  # https://anaconda.org/conda-forge/ruff?version=0.4.2
  - ruff=0.4.2
  # https://anaconda.org/conda-forge/transformers?version=4.40.2
  - transformers=4.40.2
  # https://anaconda.org/conda-forge/pytorch?version=2.1.2
  # https://github.com/huggingface/transformers/blob/v4.40.2/setup.py#L262
  - pytorch=2.1.2
  # https://anaconda.org/conda-forge/omegaconf?version=2.3.0
  - omegaconf=2.3.0
