# https://docs.astral.sh/ruff/settings/#required-version
required-version = "0.14.11"
# https://docs.astral.sh/ruff/settings/#target-version
target-version = "py310"
# https://docs.astral.sh/ruff/settings/#output-format
output-format = "full"
# https://docs.astral.sh/ruff/settings/#preview
preview = false
# https://docs.astral.sh/ruff/settings/#line-length
line-length = 120
# https://docs.astral.sh/ruff/settings/#extend-exclude
extend-exclude = ["deprecated"]

[lint]
# https://docs.astral.sh/ruff/linter/#rule-selection
# https://docs.astral.sh/ruff/settings/#lint_select
select = ["ALL"]
# https://docs.astral.sh/ruff/settings/#lint_fixable
fixable = ["ALL"]
# https://docs.astral.sh/ruff/settings/#lint_ignore
ignore = [
    # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "D",
    # https://github.com/astral-sh/ruff/blob/0.14.11/docs/formatter.md#conflicting-lint-rules (w/ formatter)
    # https://docs.astral.sh/ruff/settings/#lint_flake8-implicit-str-concat_allow-multiline
    "W191",
    "E111",
    "E114",
    "E117",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
]

# https://docs.astral.sh/ruff/settings/#lint_isort_combine-as-imports
# https://github.com/astral-sh/ruff/blob/0.14.11/docs/formatter.md#conflicting-lint-rules (w/ formatter)
[lint.isort]
combine-as-imports = true
