# https://docs.astral.sh/ruff/settings/#required-version
required-version = "0.4.2"
# https://docs.astral.sh/ruff/settings/#target-version
target-version = "py310"
# https://docs.astral.sh/ruff/settings/#output-format
output-format = "full"
# https://docs.astral.sh/ruff/settings/#preview
preview = false

[lint]
# All:
# https://docs.astral.sh/ruff/linter/#rule-selection
select = ["ALL"]
# https://docs.astral.sh/ruff/settings/#lint_fixable
fixable = ["ALL"]
# https://docs.astral.sh/ruff/settings/#lint_ignore
ignore = [
    # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "D",
    # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "W191",
    "E111",
    "E114",
    "E117",
    # "D206",
    # "D300",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
]

# Minimal:
# https://docs.astral.sh/ruff/settings/#lint_extend-select
# https://docs.astral.sh/ruff/rules/#isort-i
# extend-select = ["I"]

# https://docs.astral.sh/ruff/settings/#lint_isort_combine-as-imports
[lint.isort]
combine-as-imports = true
